name: Validate PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          tag_with_sha: true
          cache_froms: itzg/minecraft-server:latest
          push: false
